name: MinecraftUniversity
version: '${project.version}'
main: me.thevipershow.minecraftuniversity.MinecraftUniversity
api-version: '1.13'
authors: [CMarco_, TheViperShow]
description: Look up every constant of the world, from Math to Minecraft!
commands:
  constants:
    description: 'Main command to browse constants'