name: MinecraftUniversity
version: '${project.version}'
main: me.thevipershow.minecraftuniversity.MinecraftUniversity
api-version: '1.13'
authors: [CMarco_, TheViperShow]
description: 'A wonderful plugin to educate yourself on Minecraft!'
commands:
  constants:
    description: 'Main command to browse constants'
  study:
    description: 'Enable study mode'